# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
youtube: # ['@CCCP-ON-TOP']
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['https://discord.gg/b46BKPTGYk ', 'https://discord.gg/qKmE6jJgmw']
